name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-ci:
    name: Terraform CI
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Lambda deployment package
        working-directory: .
        run: |
          mkdir -p lambda_build
          cp lambda/recipe_api.py lambda_build/
          cd lambda_build
          zip -r ../lambda/recipe_api.zip .
          cd ..
          rm -rf lambda_build

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -lock=false